# Основные настройки
font=CaskaydiaCove Nerd Font Mono:size=11
pad=15x15

[cursor]
style=block
blink=yes

[colors-dark]
alpha=0.5
background=000000
foreground=ffffff

regular0=000000
regular1=ff5555
regular2=50fa7b
regular3=f1fa8c
regular4=bd93f9
regular5=ff79cc
regular6=8be9fd
regular7=ffffff

bright0=444444
bright1=ff6e67
bright2=5af78e
bright3=f4f99d
bright4=caa9fa
bright5=ff92d0
bright6=9aedfe
bright7=ffffff
